CREATE TABLE IF NOT EXISTS `quickbooks_client_customer_mapping` (
  `id` CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinic_id` CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `client_account_profile_id` CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `quickbooks_customer_id` VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `quickbooks_customer_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `quickbooks_company_name` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quickbooks_email` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `realm_id` VARCHAR(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mapping_status` ENUM('active','needs_review','archived') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `mapping_source` ENUM('manual','quickbooks_lookup') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'manual',
  `last_checked_at` DATETIME DEFAULT NULL,
  `last_error` VARCHAR(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quickbooks_client_mapping_profile` (`clinic_id`, `client_account_profile_id`),
  KEY `idx_quickbooks_client_mapping_customer` (`clinic_id`, `realm_id`, `quickbooks_customer_id`, `mapping_status`, `deleted_at`),
  KEY `idx_quickbooks_client_mapping_created_by` (`created_by`),
  KEY `idx_quickbooks_client_mapping_updated_by` (`updated_by`),
  CONSTRAINT `fk_quickbooks_mapping_workspace` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_quickbooks_mapping_profile` FOREIGN KEY (`client_account_profile_id`) REFERENCES `client_account_profile` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_quickbooks_mapping_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_quickbooks_mapping_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
