CREATE TABLE IF NOT EXISTS `clickup_category_mapping` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NOT NULL,
  `client_account_profile_id` CHAR(36) NOT NULL,
  `connection_id` CHAR(36) NULL,
  `workspace_id` VARCHAR(64) NOT NULL,
  `space_id` VARCHAR(64) NOT NULL,
  `category_key` VARCHAR(64) NOT NULL,
  `folder_id` VARCHAR(64) NULL,
  `list_id` VARCHAR(64) NOT NULL,
  `default_assignee_ids` JSON NULL,
  `mapping_status` ENUM('active','needs_review','archived') NOT NULL DEFAULT 'active',
  `mapping_source` ENUM('manual','oauth_lookup','api_lookup') NOT NULL DEFAULT 'manual',
  `created_by` CHAR(36) NULL,
  `updated_by` CHAR(36) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_clickup_category_mapping` (`clinic_id`, `client_account_profile_id`, `category_key`),
  KEY `idx_clickup_category_external` (`clinic_id`, `workspace_id`, `space_id`, `folder_id`, `list_id`),
  KEY `idx_clickup_category_status` (`clinic_id`, `mapping_status`, `updated_at`),
  KEY `fk_clickup_category_connection` (`connection_id`),
  KEY `fk_clickup_category_created_by` (`created_by`),
  KEY `fk_clickup_category_updated_by` (`updated_by`),
  CONSTRAINT `fk_clickup_category_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_category_profile` FOREIGN KEY (`client_account_profile_id`) REFERENCES `client_account_profile` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_category_connection` FOREIGN KEY (`connection_id`) REFERENCES `clickup_connection` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_category_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_category_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `clickup_priority_mapping` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NOT NULL,
  `mission_control_priority` VARCHAR(32) NOT NULL,
  `clickup_priority` TINYINT UNSIGNED NOT NULL,
  `created_by` CHAR(36) NULL,
  `updated_by` CHAR(36) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_clickup_priority_mapping` (`clinic_id`, `mission_control_priority`),
  KEY `fk_clickup_priority_created_by` (`created_by`),
  KEY `fk_clickup_priority_updated_by` (`updated_by`),
  CONSTRAINT `fk_clickup_priority_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_priority_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_priority_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_clickup_priority_value` CHECK (`clickup_priority` BETWEEN 1 AND 4)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
