CREATE TABLE IF NOT EXISTS `whatsapp_ai_setting` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinic_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `auto_send_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `business_hours_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `business_hours_start` time NOT NULL DEFAULT '09:00:00',
  `business_hours_end` time NOT NULL DEFAULT '17:30:00',
  `timezone` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Europe/London',
  `approved_tone` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT 'Warm, concise, helpful and professional. No clinical claims or guarantees.',
  `guardrails` json DEFAULT NULL,
  `confidence_threshold` decimal(3,2) NOT NULL DEFAULT '0.72',
  `human_handoff_user_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `max_auto_send_retries` int NOT NULL DEFAULT '2',
  `created_by` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_whatsapp_ai_setting_clinic` (`clinic_id`),
  KEY `fk_whatsapp_ai_setting_handoff` (`human_handoff_user_id`),
  CONSTRAINT `fk_whatsapp_ai_setting_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_whatsapp_ai_setting_handoff` FOREIGN KEY (`human_handoff_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `whatsapp_conversation` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinic_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contact_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `whatsapp_number` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
  `owner_user_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('open','human_required','closed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `last_message_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_whatsapp_conversation_contact` (`clinic_id`,`contact_id`,`whatsapp_number`),
  KEY `idx_whatsapp_conversation_clinic` (`clinic_id`,`status`,`last_message_at`),
  KEY `fk_whatsapp_conversation_owner` (`owner_user_id`),
  CONSTRAINT `fk_whatsapp_conversation_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_whatsapp_conversation_contact` FOREIGN KEY (`contact_id`) REFERENCES `contact` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_whatsapp_conversation_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `whatsapp_message` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinic_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `conversation_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contact_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `direction` enum('inbound','outbound') COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('received','read','queued','sent','failed','human_required') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'received',
  `provider_message_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `idempotency_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `failure_reason` text COLLATE utf8mb4_unicode_ci,
  `metadata` json DEFAULT NULL,
  `received_at` datetime DEFAULT NULL,
  `sent_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_whatsapp_provider_message` (`clinic_id`,`provider_message_id`),
  UNIQUE KEY `uq_whatsapp_idempotency` (`clinic_id`,`idempotency_key`),
  KEY `idx_whatsapp_message_conversation` (`conversation_id`,`created_at`),
  KEY `idx_whatsapp_message_contact` (`clinic_id`,`contact_id`,`created_at`),
  CONSTRAINT `fk_whatsapp_message_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_whatsapp_message_conversation` FOREIGN KEY (`conversation_id`) REFERENCES `whatsapp_conversation` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_whatsapp_message_contact` FOREIGN KEY (`contact_id`) REFERENCES `contact` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_whatsapp_message_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `whatsapp_ai_reply` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinic_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `conversation_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contact_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `inbound_message_id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `responsible_user_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `drafted_by_user_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `approved_by_user_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `outbound_message_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `draft_body` text COLLATE utf8mb4_unicode_ci,
  `final_body` text COLLATE utf8mb4_unicode_ci,
  `ai_output` json DEFAULT NULL,
  `confidence` decimal(3,2) NOT NULL DEFAULT '0.00',
  `provider` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'deterministic',
  `model` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('drafted','needs_approval','auto_sent','sent','human_required','failed','discarded') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'drafted',
  `guardrail_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `auto_send_allowed` tinyint(1) NOT NULL DEFAULT '0',
  `auto_send_attempted` tinyint(1) NOT NULL DEFAULT '0',
  `send_attempts` int NOT NULL DEFAULT '0',
  `failure_reason` text COLLATE utf8mb4_unicode_ci,
  `approved_at` datetime DEFAULT NULL,
  `sent_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_whatsapp_ai_reply_inbound` (`clinic_id`,`inbound_message_id`),
  KEY `idx_whatsapp_ai_reply_status` (`clinic_id`,`status`,`created_at`),
  KEY `fk_whatsapp_ai_reply_responsible` (`responsible_user_id`),
  CONSTRAINT `fk_whatsapp_ai_reply_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_whatsapp_ai_reply_conversation` FOREIGN KEY (`conversation_id`) REFERENCES `whatsapp_conversation` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_whatsapp_ai_reply_contact` FOREIGN KEY (`contact_id`) REFERENCES `contact` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_whatsapp_ai_reply_inbound` FOREIGN KEY (`inbound_message_id`) REFERENCES `whatsapp_message` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_whatsapp_ai_reply_outbound` FOREIGN KEY (`outbound_message_id`) REFERENCES `whatsapp_message` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_whatsapp_ai_reply_responsible` FOREIGN KEY (`responsible_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
