CREATE TABLE IF NOT EXISTS `clickup_connection` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NOT NULL,
  `workspace_id` VARCHAR(64) NULL,
  `workspace_name` VARCHAR(255) NULL,
  `status` ENUM('pending','connected','revoked','error') NOT NULL DEFAULT 'pending',
  `encrypted_access_token` TEXT NULL,
  `encrypted_refresh_token` TEXT NULL,
  `token_expires_at` DATETIME NULL,
  `scopes` JSON NULL,
  `oauth_state_hash` CHAR(64) NULL,
  `oauth_started_at` DATETIME NULL,
  `connected_by` CHAR(36) NULL,
  `connected_at` DATETIME NULL,
  `revoked_by` CHAR(36) NULL,
  `revoked_at` DATETIME NULL,
  `last_checked_at` DATETIME NULL,
  `last_error` VARCHAR(1000) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_clickup_connection_workspace` (`clinic_id`, `workspace_id`),
  UNIQUE KEY `uk_clickup_connection_state` (`clinic_id`, `oauth_state_hash`),
  KEY `idx_clickup_connection_status` (`clinic_id`, `status`, `updated_at`),
  KEY `fk_clickup_connection_connected_by` (`connected_by`),
  KEY `fk_clickup_connection_revoked_by` (`revoked_by`),
  CONSTRAINT `fk_clickup_connection_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_connection_connected_by` FOREIGN KEY (`connected_by`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_connection_revoked_by` FOREIGN KEY (`revoked_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `clickup_client_mapping` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NOT NULL,
  `client_account_profile_id` CHAR(36) NOT NULL,
  `connection_id` CHAR(36) NULL,
  `workspace_id` VARCHAR(64) NOT NULL,
  `space_id` VARCHAR(64) NULL,
  `folder_id` VARCHAR(64) NULL,
  `list_id` VARCHAR(64) NULL,
  `delivery_root_task_id` VARCHAR(64) NULL,
  `delivery_url` VARCHAR(1000) NULL,
  `mapping_status` ENUM('active','needs_review','archived') NOT NULL DEFAULT 'active',
  `mapping_source` ENUM('manual','oauth_lookup','api_lookup') NOT NULL DEFAULT 'manual',
  `created_by` CHAR(36) NULL,
  `updated_by` CHAR(36) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_clickup_client_profile` (`clinic_id`, `client_account_profile_id`),
  KEY `idx_clickup_client_external` (`clinic_id`, `workspace_id`, `space_id`, `folder_id`, `list_id`, `delivery_root_task_id`),
  KEY `idx_clickup_client_status` (`clinic_id`, `mapping_status`, `updated_at`),
  KEY `fk_clickup_client_mapping_connection` (`connection_id`),
  KEY `fk_clickup_client_mapping_created_by` (`created_by`),
  KEY `fk_clickup_client_mapping_updated_by` (`updated_by`),
  CONSTRAINT `fk_clickup_client_mapping_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_client_mapping_profile` FOREIGN KEY (`client_account_profile_id`) REFERENCES `client_account_profile` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_client_mapping_connection` FOREIGN KEY (`connection_id`) REFERENCES `clickup_connection` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_client_mapping_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_client_mapping_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `clickup_task_mapping` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NOT NULL,
  `client_account_profile_id` CHAR(36) NOT NULL,
  `internal_task_id` CHAR(36) NULL,
  `connection_id` CHAR(36) NULL,
  `workspace_id` VARCHAR(64) NOT NULL,
  `clickup_task_id` VARCHAR(64) NOT NULL,
  `clickup_list_id` VARCHAR(64) NULL,
  `clickup_url` VARCHAR(1000) NULL,
  `sync_direction` ENUM('mission_control_to_clickup','clickup_to_mission_control','manual') NOT NULL DEFAULT 'manual',
  `mapping_status` ENUM('active','needs_review','archived') NOT NULL DEFAULT 'active',
  `created_by` CHAR(36) NULL,
  `updated_by` CHAR(36) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_clickup_task_external` (`clinic_id`, `workspace_id`, `clickup_task_id`),
  UNIQUE KEY `uk_clickup_task_internal` (`clinic_id`, `internal_task_id`),
  KEY `idx_clickup_task_client` (`clinic_id`, `client_account_profile_id`, `mapping_status`),
  KEY `fk_clickup_task_mapping_connection` (`connection_id`),
  KEY `fk_clickup_task_mapping_created_by` (`created_by`),
  KEY `fk_clickup_task_mapping_updated_by` (`updated_by`),
  CONSTRAINT `fk_clickup_task_mapping_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_task_mapping_profile` FOREIGN KEY (`client_account_profile_id`) REFERENCES `client_account_profile` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_task_mapping_task` FOREIGN KEY (`internal_task_id`) REFERENCES `task` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_task_mapping_connection` FOREIGN KEY (`connection_id`) REFERENCES `clickup_connection` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_task_mapping_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_task_mapping_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
