CREATE TABLE IF NOT EXISTS `proposal_signature_request` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NOT NULL,
  `proposal_id` CHAR(36) NOT NULL,
  `provider` VARCHAR(50) NOT NULL DEFAULT 'log',
  `provider_request_id` VARCHAR(191) NULL,
  `status` ENUM('requested','sent','viewed','signed','declined','expired','cancelled','failed') NOT NULL DEFAULT 'requested',
  `signer_name` VARCHAR(255) NULL,
  `signer_email` VARCHAR(255) NULL,
  `signature_url` VARCHAR(1000) NULL,
  `idempotency_key` VARCHAR(191) NOT NULL,
  `requested_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sent_at` DATETIME NULL,
  `viewed_at` DATETIME NULL,
  `signed_at` DATETIME NULL,
  `declined_at` DATETIME NULL,
  `expired_at` DATETIME NULL,
  `failure_reason` VARCHAR(1000) NULL,
  `created_by` CHAR(36) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_proposal_signature_request_idempotency` (`clinic_id`, `idempotency_key`),
  UNIQUE KEY `uk_proposal_signature_request_provider` (`provider`, `provider_request_id`),
  KEY `idx_proposal_signature_request_proposal` (`clinic_id`, `proposal_id`, `created_at`),
  KEY `idx_proposal_signature_request_status` (`clinic_id`, `status`, `updated_at`),
  KEY `fk_proposal_signature_request_created_by` (`created_by`),
  CONSTRAINT `fk_proposal_signature_request_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_signature_request_proposal` FOREIGN KEY (`proposal_id`) REFERENCES `proposal` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_signature_request_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `proposal_signature_event` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NOT NULL,
  `proposal_id` CHAR(36) NOT NULL,
  `signature_request_id` CHAR(36) NOT NULL,
  `provider` VARCHAR(50) NOT NULL,
  `provider_event_id` VARCHAR(191) NOT NULL,
  `event_type` VARCHAR(100) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `signer_name` VARCHAR(255) NULL,
  `signer_email` VARCHAR(255) NULL,
  `signed_pdf_url` VARCHAR(1000) NULL,
  `audit_certificate_url` VARCHAR(1000) NULL,
  `raw_payload_sha256` CHAR(64) NOT NULL,
  `raw_payload_json` JSON NULL,
  `received_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_proposal_signature_event_provider` (`provider`, `provider_event_id`),
  KEY `idx_proposal_signature_event_request` (`signature_request_id`, `received_at`),
  KEY `idx_proposal_signature_event_proposal` (`clinic_id`, `proposal_id`, `received_at`),
  CONSTRAINT `fk_proposal_signature_event_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_signature_event_proposal` FOREIGN KEY (`proposal_id`) REFERENCES `proposal` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_signature_event_request` FOREIGN KEY (`signature_request_id`) REFERENCES `proposal_signature_request` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `proposal_signature_evidence` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NOT NULL,
  `proposal_id` CHAR(36) NOT NULL,
  `signature_request_id` CHAR(36) NOT NULL,
  `provider` VARCHAR(50) NOT NULL,
  `provider_request_id` VARCHAR(191) NULL,
  `signer_name` VARCHAR(255) NOT NULL,
  `signer_email` VARCHAR(255) NOT NULL,
  `signed_at` DATETIME NOT NULL,
  `signed_pdf_url` VARCHAR(1000) NULL,
  `audit_certificate_url` VARCHAR(1000) NULL,
  `evidence_sha256` CHAR(64) NOT NULL,
  `evidence_json` JSON NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_proposal_signature_evidence_request` (`signature_request_id`),
  KEY `idx_proposal_signature_evidence_proposal` (`clinic_id`, `proposal_id`, `signed_at`),
  CONSTRAINT `fk_proposal_signature_evidence_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_signature_evidence_proposal` FOREIGN KEY (`proposal_id`) REFERENCES `proposal` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_signature_evidence_request` FOREIGN KEY (`signature_request_id`) REFERENCES `proposal_signature_request` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
