CREATE TABLE IF NOT EXISTS `clickup_webhook_event` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NULL,
  `connection_id` CHAR(36) NULL,
  `client_account_profile_id` CHAR(36) NULL,
  `task_mapping_id` CHAR(36) NULL,
  `workspace_id` VARCHAR(64) NULL,
  `webhook_id` VARCHAR(128) NOT NULL,
  `provider_event_key` VARCHAR(255) NOT NULL,
  `provider_event_type` VARCHAR(80) NOT NULL,
  `provider_event_version` VARCHAR(40) NOT NULL DEFAULT 'v1',
  `clickup_task_id` VARCHAR(64) NULL,
  `clickup_list_id` VARCHAR(64) NULL,
  `event_occurred_at` DATETIME NULL,
  `provider_updated_at` DATETIME NULL,
  `payload_hash` CHAR(64) NOT NULL,
  `payload_summary` JSON NULL,
  `processing_status` ENUM('queued','processing','processed','duplicate','stale','quarantined','retrying','dead_letter','failed','ignored') NOT NULL DEFAULT 'queued',
  `retry_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `next_retry_at` DATETIME NULL,
  `error_class` VARCHAR(80) NULL,
  `error_message` VARCHAR(1000) NULL,
  `received_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `processed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_clickup_webhook_event_key` (`provider_event_key`),
  KEY `idx_clickup_webhook_event_status` (`processing_status`, `next_retry_at`, `received_at`),
  KEY `idx_clickup_webhook_event_client` (`clinic_id`, `client_account_profile_id`, `processing_status`),
  KEY `idx_clickup_webhook_event_task` (`clinic_id`, `workspace_id`, `clickup_task_id`, `event_occurred_at`),
  KEY `fk_clickup_webhook_event_connection` (`connection_id`),
  KEY `fk_clickup_webhook_event_profile` (`client_account_profile_id`),
  KEY `fk_clickup_webhook_event_mapping` (`task_mapping_id`),
  CONSTRAINT `fk_clickup_webhook_event_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_webhook_event_connection` FOREIGN KEY (`connection_id`) REFERENCES `clickup_connection` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_webhook_event_profile` FOREIGN KEY (`client_account_profile_id`) REFERENCES `client_account_profile` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_webhook_event_mapping` FOREIGN KEY (`task_mapping_id`) REFERENCES `clickup_task_mapping` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `clickup_task_state_cache` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NOT NULL,
  `client_account_profile_id` CHAR(36) NOT NULL,
  `task_mapping_id` CHAR(36) NOT NULL,
  `workspace_id` VARCHAR(64) NOT NULL,
  `clickup_task_id` VARCHAR(64) NOT NULL,
  `clickup_list_id` VARCHAR(64) NULL,
  `clickup_status` VARCHAR(120) NULL,
  `clickup_status_type` VARCHAR(80) NULL,
  `clickup_priority` VARCHAR(80) NULL,
  `clickup_due_at` DATETIME NULL,
  `clickup_assignee_ids` JSON NULL,
  `provider_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `provider_archived` TINYINT(1) NOT NULL DEFAULT 0,
  `provider_moved` TINYINT(1) NOT NULL DEFAULT 0,
  `provider_updated_at` DATETIME NULL,
  `last_event_key` VARCHAR(255) NULL,
  `last_event_type` VARCHAR(80) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_clickup_task_state_mapping` (`task_mapping_id`),
  UNIQUE KEY `uk_clickup_task_state_external` (`clinic_id`, `workspace_id`, `clickup_task_id`),
  KEY `idx_clickup_task_state_client` (`clinic_id`, `client_account_profile_id`, `updated_at`),
  CONSTRAINT `fk_clickup_task_state_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_task_state_profile` FOREIGN KEY (`client_account_profile_id`) REFERENCES `client_account_profile` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_task_state_mapping` FOREIGN KEY (`task_mapping_id`) REFERENCES `clickup_task_mapping` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `clickup_sync_checkpoint` (
  `id` CHAR(36) NOT NULL,
  `clinic_id` CHAR(36) NOT NULL,
  `connection_id` CHAR(36) NULL,
  `client_account_profile_id` CHAR(36) NOT NULL,
  `workspace_id` VARCHAR(64) NOT NULL,
  `clickup_list_id` VARCHAR(64) NULL,
  `sync_status` ENUM('healthy','delayed','retrying','dead_letter','disconnected','reconciliation_needed') NOT NULL DEFAULT 'healthy',
  `last_event_at` DATETIME NULL,
  `last_processed_event_at` DATETIME NULL,
  `last_reconciled_at` DATETIME NULL,
  `last_error` VARCHAR(1000) NULL,
  `retrying_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `dead_letter_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `reconciliation_cursor` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_clickup_sync_checkpoint_client` (`clinic_id`, `client_account_profile_id`, `workspace_id`, `clickup_list_id`),
  KEY `idx_clickup_sync_checkpoint_status` (`clinic_id`, `sync_status`, `updated_at`),
  KEY `fk_clickup_sync_checkpoint_connection` (`connection_id`),
  KEY `fk_clickup_sync_checkpoint_profile` (`client_account_profile_id`),
  CONSTRAINT `fk_clickup_sync_checkpoint_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_clickup_sync_checkpoint_connection` FOREIGN KEY (`connection_id`) REFERENCES `clickup_connection` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_clickup_sync_checkpoint_profile` FOREIGN KEY (`client_account_profile_id`) REFERENCES `client_account_profile` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
