CREATE TABLE IF NOT EXISTS `proposal_discovery_session` (
  `id` CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinic_id` CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contact_id` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deal_id` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_account_profile_id` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `proposal_id` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` ENUM('in_progress','paused','completed','draft_created','archived') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'in_progress',
  `clinic_type` VARCHAR(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `recommended_package_id` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `active_constraint_id` VARCHAR(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `selected_media_spend_cents` INT DEFAULT NULL,
  `prefill_snapshot` JSON DEFAULT NULL,
  `answers` JSON DEFAULT NULL,
  `free_notes` MEDIUMTEXT COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `missing_fields` JSON DEFAULT NULL,
  `conflicts` JSON DEFAULT NULL,
  `call_outcome` VARCHAR(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `next_action` VARCHAR(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `next_action_owner_id` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `next_action_due_at` DATETIME DEFAULT NULL,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_autosaved_at` DATETIME DEFAULT NULL,
  `completed_at` DATETIME DEFAULT NULL,
  `created_by` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_by` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_proposal_discovery_clinic_status` (`clinic_id`, `status`, `updated_at`),
  KEY `idx_proposal_discovery_contact` (`clinic_id`, `contact_id`, `status`),
  KEY `idx_proposal_discovery_account` (`clinic_id`, `client_account_profile_id`, `status`),
  KEY `idx_proposal_discovery_proposal` (`clinic_id`, `proposal_id`),
  KEY `fk_proposal_discovery_deal` (`deal_id`),
  KEY `fk_proposal_discovery_package` (`recommended_package_id`),
  KEY `fk_proposal_discovery_created_by` (`created_by`),
  KEY `fk_proposal_discovery_updated_by` (`updated_by`),
  CONSTRAINT `fk_proposal_discovery_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_discovery_contact` FOREIGN KEY (`contact_id`) REFERENCES `contact` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_proposal_discovery_deal` FOREIGN KEY (`deal_id`) REFERENCES `deal` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_proposal_discovery_account` FOREIGN KEY (`client_account_profile_id`) REFERENCES `client_account_profile` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_proposal_discovery_proposal` FOREIGN KEY (`proposal_id`) REFERENCES `proposal` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_proposal_discovery_package` FOREIGN KEY (`recommended_package_id`) REFERENCES `growth_package` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_proposal_discovery_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_proposal_discovery_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `proposal_discovery_answer_source` (
  `id` CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinic_id` CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `session_id` CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `field_key` VARCHAR(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `state` ENUM('known','working_diagnosis','provisional','to_confirm') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'to_confirm',
  `source_label` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_at` DATETIME DEFAULT NULL,
  `customer_wording` TEXT COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `value_snapshot` JSON DEFAULT NULL,
  `updated_by` CHAR(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_proposal_discovery_answer_field` (`session_id`, `field_key`),
  KEY `idx_proposal_discovery_answer_clinic` (`clinic_id`, `field_key`, `state`),
  KEY `fk_proposal_discovery_answer_updated_by` (`updated_by`),
  CONSTRAINT `fk_proposal_discovery_answer_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_discovery_answer_session` FOREIGN KEY (`session_id`) REFERENCES `proposal_discovery_session` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_discovery_answer_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
