-- CG-161: structured freelancer report evidence and QA controls.
CREATE TABLE IF NOT EXISTS `freelancer_report_review` (
  `id` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinic_id` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `work_type` ENUM('ppc','seo','gbp','wordpress_development','design_video','reporting') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_event_id` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `report_title` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `account_label` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reporting_period_start` DATE NOT NULL,
  `reporting_period_end` DATE NOT NULL,
  `metrics` JSON NOT NULL,
  `evidence` JSON NOT NULL,
  `risks` JSON NOT NULL,
  `recommended_actions` JSON NOT NULL,
  `source_links` JSON NOT NULL,
  `qa_status` ENUM('awaiting_evidence','awaiting_qa','accepted','failed_qa','rejected') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'awaiting_evidence',
  `qa_notes` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `high_risk_change` TINYINT(1) NOT NULL DEFAULT 0,
  `reviewer_id` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `verification_date` DATE DEFAULT NULL,
  `created_by` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_freelancer_report_review_source` (`clinic_id`, `work_type`, `source_event_id`),
  KEY `idx_freelancer_report_review_status` (`clinic_id`, `qa_status`, `updated_at`),
  KEY `idx_freelancer_report_review_work_type` (`clinic_id`, `work_type`, `reporting_period_end`),
  CONSTRAINT `fk_freelancer_report_review_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
