-- MC-039: Accepted proposal snapshot and basic SOW/commercial record.
SET @schema_name = DATABASE();

CREATE TABLE IF NOT EXISTS `proposal_acceptance_record` (
  `id` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `clinic_id` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `proposal_id` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `contact_id` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deal_id` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `client_account_profile_id` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accepted_by_name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accepted_by_email` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `accepted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `acceptance_status` ENUM('accepted','won') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'accepted',
  `package_name` VARCHAR(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `recommended_package_id` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `monthly_fee_cents` INT DEFAULT NULL,
  `setup_fee_cents` INT DEFAULT NULL,
  `currency` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'GBP',
  `payment_terms` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `start_date` DATE DEFAULT NULL,
  `minimum_term_months` INT DEFAULT NULL,
  `notice_period_days` INT DEFAULT NULL,
  `scope` JSON DEFAULT NULL,
  `commercial_snapshot` JSON DEFAULT NULL,
  `proposal_snapshot` JSON DEFAULT NULL,
  `created_by` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_proposal_acceptance_proposal` (`proposal_id`),
  KEY `idx_proposal_acceptance_clinic` (`clinic_id`, `accepted_at`),
  KEY `idx_proposal_acceptance_client_account` (`client_account_profile_id`, `accepted_at`),
  KEY `idx_proposal_acceptance_contact` (`clinic_id`, `contact_id`, `accepted_at`),
  KEY `idx_proposal_acceptance_deal` (`clinic_id`, `deal_id`, `accepted_at`),
  KEY `idx_proposal_acceptance_package` (`clinic_id`, `package_name`, `accepted_at`),
  KEY `fk_proposal_acceptance_recommended_package` (`recommended_package_id`),
  KEY `fk_proposal_acceptance_created_by` (`created_by`),
  CONSTRAINT `fk_proposal_acceptance_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_acceptance_proposal` FOREIGN KEY (`proposal_id`) REFERENCES `proposal` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_proposal_acceptance_contact` FOREIGN KEY (`contact_id`) REFERENCES `contact` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_proposal_acceptance_deal` FOREIGN KEY (`deal_id`) REFERENCES `deal` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_proposal_acceptance_client_account` FOREIGN KEY (`client_account_profile_id`) REFERENCES `client_account_profile` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_proposal_acceptance_recommended_package` FOREIGN KEY (`recommended_package_id`) REFERENCES `growth_package` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_proposal_acceptance_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
