CREATE TABLE IF NOT EXISTS performance_alert (
  id CHAR(36) COLLATE utf8mb4_unicode_ci PRIMARY KEY,
  clinic_id CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  type VARCHAR(80) NOT NULL,
  severity ENUM('low', 'medium', 'high', 'critical') NOT NULL DEFAULT 'medium',
  title VARCHAR(255) NOT NULL,
  summary TEXT NULL,
  source_type VARCHAR(80) NULL,
  source_id CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  source_contact_id CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  insight_id CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  status ENUM('open', 'acknowledged', 'resolved', 'archived') NOT NULL DEFAULT 'open',
  metadata JSON NULL,
  created_by CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  acknowledged_at DATETIME NULL,
  resolved_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  KEY idx_performance_alert_clinic_status (clinic_id, status, deleted_at),
  KEY idx_performance_alert_type (clinic_id, type),
  KEY idx_performance_alert_source (clinic_id, source_type, source_id),
  KEY idx_performance_alert_contact (source_contact_id),
  KEY idx_performance_alert_insight (insight_id),
  CONSTRAINT fk_performance_alert_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id) ON DELETE CASCADE,
  CONSTRAINT fk_performance_alert_contact FOREIGN KEY (source_contact_id) REFERENCES contact(id) ON DELETE SET NULL,
  CONSTRAINT fk_performance_alert_insight FOREIGN KEY (insight_id) REFERENCES insight(id) ON DELETE SET NULL,
  CONSTRAINT fk_performance_alert_created_by FOREIGN KEY (created_by) REFERENCES user(id) ON DELETE SET NULL
);
