CREATE TABLE IF NOT EXISTS communication_sequence_enrollment (
  id CHAR(36) PRIMARY KEY,
  clinic_id CHAR(36) NOT NULL,
  sequence_id CHAR(36) NOT NULL,
  contact_id CHAR(36) NOT NULL,
  status ENUM('active', 'completed', 'unenrolled', 'failed') NOT NULL DEFAULT 'active',
  current_step_index INT NOT NULL DEFAULT 0,
  next_step_at DATETIME NULL,
  send_on_weekends TINYINT(1) NOT NULL DEFAULT 0,
  timezone VARCHAR(100) NOT NULL DEFAULT 'UTC',
  last_error TEXT NULL,
  enrolled_by CHAR(36) NULL,
  unenrolled_by CHAR(36) NULL,
  unenrolled_at DATETIME NULL,
  completed_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_sequence_enrollment_contact (clinic_id, sequence_id, contact_id),
  KEY idx_sequence_enrollment_due (status, next_step_at),
  KEY idx_sequence_enrollment_sequence (clinic_id, sequence_id, status),
  KEY idx_sequence_enrollment_contact (clinic_id, contact_id, status),
  CONSTRAINT fk_cse_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cse_sequence FOREIGN KEY (sequence_id) REFERENCES communication_sequence(id) ON DELETE CASCADE,
  CONSTRAINT fk_cse_contact FOREIGN KEY (contact_id) REFERENCES contact(id) ON DELETE CASCADE,
  CONSTRAINT fk_cse_enrolled_by FOREIGN KEY (enrolled_by) REFERENCES user(id) ON DELETE SET NULL,
  CONSTRAINT fk_cse_unenrolled_by FOREIGN KEY (unenrolled_by) REFERENCES user(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS communication_sequence_step_run (
  id CHAR(36) PRIMARY KEY,
  clinic_id CHAR(36) NOT NULL,
  enrollment_id CHAR(36) NOT NULL,
  sequence_id CHAR(36) NOT NULL,
  contact_id CHAR(36) NOT NULL,
  step_index INT NOT NULL,
  channel VARCHAR(40) NOT NULL,
  status ENUM('pending', 'sent', 'skipped', 'failed') NOT NULL DEFAULT 'pending',
  scheduled_at DATETIME NOT NULL,
  sent_at DATETIME NULL,
  message_id CHAR(36) NULL,
  error_message TEXT NULL,
  metadata JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_sequence_step_run (enrollment_id, step_index),
  KEY idx_sequence_step_run_sequence (clinic_id, sequence_id, status),
  KEY idx_sequence_step_run_contact (clinic_id, contact_id),
  CONSTRAINT fk_cssr_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cssr_enrollment FOREIGN KEY (enrollment_id) REFERENCES communication_sequence_enrollment(id) ON DELETE CASCADE,
  CONSTRAINT fk_cssr_sequence FOREIGN KEY (sequence_id) REFERENCES communication_sequence(id) ON DELETE CASCADE,
  CONSTRAINT fk_cssr_contact FOREIGN KEY (contact_id) REFERENCES contact(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
