CREATE TABLE IF NOT EXISTS `webhook_endpoint` (
  `id` char(36) NOT NULL,
  `clinic_id` char(36) NOT NULL,
  `url` varchar(500) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `events` json NOT NULL,
  `secret_hash` char(64) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `created_by` char(36) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_webhook_endpoint_clinic` (`clinic_id`),
  KEY `idx_webhook_endpoint_active` (`is_active`),
  KEY `idx_webhook_endpoint_deleted` (`deleted_at`),
  CONSTRAINT `fk_webhook_endpoint_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_webhook_endpoint_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `message_template` (
  `id` char(36) NOT NULL,
  `clinic_id` char(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `channel` enum('email','sms','whatsapp') NOT NULL DEFAULT 'email',
  `subject` varchar(500) DEFAULT NULL,
  `body` longtext NOT NULL,
  `status` enum('draft','active','archived') NOT NULL DEFAULT 'draft',
  `created_by` char(36) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_message_template_name` (`clinic_id`, `name`),
  KEY `idx_message_template_clinic` (`clinic_id`),
  KEY `idx_message_template_channel` (`channel`),
  KEY `idx_message_template_status` (`status`),
  KEY `idx_message_template_deleted` (`deleted_at`),
  CONSTRAINT `fk_message_template_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_message_template_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
