CREATE TABLE IF NOT EXISTS client_account_service (
  id CHAR(36) NOT NULL PRIMARY KEY,
  clinic_id CHAR(36) NOT NULL,
  client_account_profile_id CHAR(36) NOT NULL,
  service_type ENUM('ppc', 'seo', 'gbp', 'website', 'landing_pages', 'cro', 'strategy', 'other') NOT NULL,
  name VARCHAR(150) NOT NULL,
  status ENUM('onboarding', 'active', 'paused', 'ended', 'archived') NOT NULL DEFAULT 'onboarding',
  start_date DATE NULL,
  renewal_date DATE NULL,
  end_date DATE NULL,
  owner_id CHAR(36) NULL,
  recurring_value DECIMAL(12,2) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  contract_status ENUM('active', 'trial', 'pending', 'paused', 'cancelled', 'expired') NOT NULL DEFAULT 'pending',
  notes TEXT NULL,
  archived_at DATETIME NULL,
  created_by CHAR(36) NULL,
  updated_by CHAR(36) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_client_account_service_profile (client_account_profile_id),
  KEY idx_client_account_service_clinic_status (clinic_id, status, archived_at),
  KEY idx_client_account_service_renewal (clinic_id, renewal_date, contract_status),
  KEY idx_client_account_service_owner (owner_id),
  CONSTRAINT fk_client_account_service_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id) ON DELETE CASCADE,
  CONSTRAINT fk_client_account_service_profile FOREIGN KEY (client_account_profile_id) REFERENCES client_account_profile(id) ON DELETE CASCADE,
  CONSTRAINT fk_client_account_service_owner FOREIGN KEY (owner_id) REFERENCES user(id) ON DELETE SET NULL,
  CONSTRAINT fk_client_account_service_created_by FOREIGN KEY (created_by) REFERENCES user(id) ON DELETE SET NULL,
  CONSTRAINT fk_client_account_service_updated_by FOREIGN KEY (updated_by) REFERENCES user(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
