CREATE TABLE IF NOT EXISTS monthly_action_plan (
  id CHAR(36) COLLATE utf8mb4_unicode_ci PRIMARY KEY,
  clinic_id CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  plan_month DATE NOT NULL,
  status ENUM('draft', 'active', 'completed', 'archived') NOT NULL DEFAULT 'draft',
  title VARCHAR(255) NOT NULL,
  summary TEXT NULL,
  focus_metric VARCHAR(120) NULL,
  created_by CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  KEY idx_monthly_action_plan_clinic_month (clinic_id, plan_month, deleted_at),
  KEY idx_monthly_action_plan_status (clinic_id, status, deleted_at),
  KEY fk_monthly_action_plan_created_by (created_by),
  CONSTRAINT fk_monthly_action_plan_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id) ON DELETE CASCADE,
  CONSTRAINT fk_monthly_action_plan_created_by FOREIGN KEY (created_by) REFERENCES user(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS monthly_action_plan_item (
  id CHAR(36) COLLATE utf8mb4_unicode_ci PRIMARY KEY,
  plan_id CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  clinic_id CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  task_id CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  insight_id CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  source_type VARCHAR(80) NULL,
  source_id CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  title VARCHAR(255) NOT NULL,
  recommended_action TEXT NULL,
  priority ENUM('low', 'medium', 'high') NOT NULL DEFAULT 'medium',
  status ENUM('planned', 'in_progress', 'completed', 'skipped') NOT NULL DEFAULT 'planned',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  KEY idx_monthly_action_plan_item_plan_status (plan_id, status, deleted_at),
  KEY idx_monthly_action_plan_item_clinic (clinic_id, deleted_at),
  KEY idx_monthly_action_plan_item_task (task_id),
  KEY idx_monthly_action_plan_item_insight (insight_id),
  KEY idx_monthly_action_plan_item_source (clinic_id, source_type, source_id),
  CONSTRAINT fk_monthly_action_plan_item_plan FOREIGN KEY (plan_id) REFERENCES monthly_action_plan(id) ON DELETE CASCADE,
  CONSTRAINT fk_monthly_action_plan_item_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id) ON DELETE CASCADE,
  CONSTRAINT fk_monthly_action_plan_item_task FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE SET NULL,
  CONSTRAINT fk_monthly_action_plan_item_insight FOREIGN KEY (insight_id) REFERENCES insight(id) ON DELETE SET NULL
);
