CREATE TABLE IF NOT EXISTS `api_key` (
  `id` char(36) NOT NULL,
  `clinic_id` char(36) NOT NULL,
  `name` varchar(100) NOT NULL,
  `key_prefix` varchar(32) NOT NULL,
  `key_hash` char(64) NOT NULL,
  `created_by` char(36) DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `revoked_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_api_key_hash` (`key_hash`),
  KEY `idx_api_key_clinic` (`clinic_id`),
  KEY `idx_api_key_revoked` (`revoked_at`),
  CONSTRAINT `fk_api_key_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_api_key_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `treatment_catalog` (
  `id` char(36) NOT NULL,
  `clinic_id` char(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(50) NOT NULL DEFAULT 'Other',
  `duration_minutes` int DEFAULT NULL,
  `price_cents` int DEFAULT NULL,
  `average_value_cents` int DEFAULT NULL,
  `margin_percent` decimal(5,2) DEFAULT NULL,
  `priority` int NOT NULL DEFAULT 0,
  `is_high_ticket` tinyint(1) NOT NULL DEFAULT 0,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_by` char(36) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_treatment_catalog_name` (`clinic_id`, `name`),
  KEY `idx_treatment_catalog_clinic` (`clinic_id`),
  KEY `idx_treatment_catalog_category` (`clinic_id`, `category`),
  KEY `idx_treatment_catalog_priority` (`clinic_id`, `priority`),
  KEY `idx_treatment_catalog_status` (`status`),
  KEY `idx_treatment_catalog_deleted` (`deleted_at`),
  CONSTRAINT `fk_treatment_catalog_clinic` FOREIGN KEY (`clinic_id`) REFERENCES `clinic` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_treatment_catalog_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
