CREATE TABLE IF NOT EXISTS insight (
  id CHAR(36) COLLATE utf8mb4_unicode_ci PRIMARY KEY,
  clinic_id CHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  type VARCHAR(80) NOT NULL,
  severity ENUM('low', 'medium', 'high', 'critical') NOT NULL DEFAULT 'medium',
  title VARCHAR(255) NOT NULL,
  summary TEXT NULL,
  recommended_action TEXT NULL,
  source_type VARCHAR(80) NULL,
  source_id CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  source_contact_id CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  status ENUM('open', 'in_progress', 'resolved', 'archived') NOT NULL DEFAULT 'open',
  assigned_to CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  due_date DATE NULL,
  generated_from VARCHAR(100) NULL,
  dedupe_key VARCHAR(255) NULL,
  metadata JSON NULL,
  created_by CHAR(36) COLLATE utf8mb4_unicode_ci NULL,
  resolved_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  KEY idx_insight_clinic_status (clinic_id, status, deleted_at),
  KEY idx_insight_clinic_type (clinic_id, type),
  KEY idx_insight_source (clinic_id, source_type, source_id),
  KEY idx_insight_dedupe (clinic_id, dedupe_key),
  KEY idx_insight_assigned_to (assigned_to),
  KEY idx_insight_source_contact (source_contact_id),
  CONSTRAINT fk_insight_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id) ON DELETE CASCADE,
  CONSTRAINT fk_insight_assigned_to FOREIGN KEY (assigned_to) REFERENCES user(id) ON DELETE SET NULL,
  CONSTRAINT fk_insight_created_by FOREIGN KEY (created_by) REFERENCES user(id) ON DELETE SET NULL,
  CONSTRAINT fk_insight_source_contact FOREIGN KEY (source_contact_id) REFERENCES contact(id) ON DELETE SET NULL
);
