CREATE TABLE IF NOT EXISTS integration_raw_payload (
  id CHAR(36) NOT NULL,
  clinic_id CHAR(36) NOT NULL,
  source VARCHAR(100) NOT NULL,
  source_event_id VARCHAR(255) NULL,
  linked_entity_type VARCHAR(100) NULL,
  linked_entity_id CHAR(36) NULL,
  payload JSON NOT NULL,
  received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMP NULL,
  status ENUM('received', 'processed', 'failed') NOT NULL DEFAULT 'received',
  error_message VARCHAR(500) NULL,
  created_by CHAR(36) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_integration_raw_payload_event (clinic_id, source, source_event_id),
  KEY idx_integration_raw_payload_clinic_source (clinic_id, source, received_at),
  KEY idx_integration_raw_payload_linked (linked_entity_type, linked_entity_id),
  CONSTRAINT fk_integration_raw_payload_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id) ON DELETE CASCADE,
  CONSTRAINT fk_integration_raw_payload_created_by FOREIGN KEY (created_by) REFERENCES user(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS manual_platform_metric (
  id CHAR(36) NOT NULL,
  clinic_id CHAR(36) NOT NULL,
  platform ENUM('google_ads', 'ga4', 'google_business_profile', 'meta', 'seo', 'other') NOT NULL,
  metric_date DATE NOT NULL,
  campaign VARCHAR(255) NULL,
  location_label VARCHAR(255) NULL,
  metric_name VARCHAR(150) NOT NULL,
  metric_value DECIMAL(14, 2) NOT NULL DEFAULT 0,
  unit VARCHAR(50) NULL,
  attribution_label VARCHAR(255) NULL,
  raw_payload JSON NULL,
  notes TEXT NULL,
  created_by CHAR(36) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_manual_platform_metric_reporting (clinic_id, platform, metric_date, metric_name, deleted_at),
  KEY idx_manual_platform_metric_campaign (clinic_id, campaign, metric_date, deleted_at),
  CONSTRAINT fk_manual_platform_metric_clinic FOREIGN KEY (clinic_id) REFERENCES clinic(id) ON DELETE CASCADE,
  CONSTRAINT fk_manual_platform_metric_created_by FOREIGN KEY (created_by) REFERENCES user(id) ON DELETE SET NULL
);
