import {
  apiRequest,
  configureApiAuthRefresh,
  ApiClientError,
} from "@/lib/api-client/core";
import {
  clearStoredAuthSession,
  getStoredAuthSession,
  refreshStoredAuthSession,
  saveAuthSession,
  storeAuthSession,
  toAuthUser,
  toStoredSession,
} from "@/lib/api-client/auth-session";
import { createAccountApi } from "@/lib/api-client/account-api";
import { createAutomationsApi } from "@/lib/api-client/automations-api";
import { createClinicSetupApi } from "@/lib/api-client/clinic-setup-api";
import { createCommandPaletteApi } from "@/lib/api-client/command-palette-api";
import { createCatalogApi } from "@/lib/api-client/catalog-api";
import { createComplianceApi } from "@/lib/api-client/compliance-api";
import { createDeveloperSettingsApi } from "@/lib/api-client/developer-settings-api";
import { createFormsApi } from "@/lib/api-client/forms-api";
import { createGrowthScoresApi } from "@/lib/api-client/growth-scores-api";
import { createLocationsIntegrationsApi } from "@/lib/api-client/locations-integrations-api";
import { createOperationsApi } from "@/lib/api-client/operations-api";
import { createPackagesApi } from "@/lib/api-client/packages-api";
import { createProposalsApi } from "@/lib/api-client/proposals-api";
import { createSequencesApi } from "@/lib/api-client/sequences-api";
import { createSopsApi } from "@/lib/api-client/sops-api";

export { ApiClientError };
export {
  clearStoredAuthSession,
  getStoredAuthSession,
  storeAuthSession,
  toAuthUser,
};

export type {
  ApiEnvelope,
  ApiKeyRecord,
  AiProjectRecord,
  AiRunRecord,
  BackgroundJobsResponse,
  ClientAccountChurnRisk,
  ClientAccountContractStatus,
  ClientAccountDriveFolderPayload,
  ClientAccountHealthStatus,
  ClientAccountListParams,
  ClientAccountOnboardingStatus,
  ClientAccountPerson,
  ClientAccountProfilePayload,
  ClientAccountProfileRecord,
  ClientAccountServiceListParams,
  ClientAccountServicePayload,
  ClientAccountServiceRecord,
  ClientAccountServiceStatus,
  ClientAccountServiceType,
  ClientAccountServiceUpdatePayload,
  ClientAccountSummaryRecord,
  AuditLogList,
  AutomationRecord,
  BackendAuthResponse,
  BackendAuthUser,
  BackendClinicMembership,
  BackendSecurityEvent,
  BackendSession,
  BackendTeamRole,
  AppointmentListParams,
  AppointmentClinicianRecord,
  AppointmentAvailabilityParams,
  AppointmentAvailabilityRecord,
  AppointmentAvailabilitySlot,
  AppointmentPayload,
  AppointmentRecord,
  AppointmentStatus,
  AppointmentUpdatePayload,
  BillingCheckoutSession,
  BillingStatus,
  ClinicProfile,
  ComplianceDocumentRecord,
  ComplianceSettingsRecord,
  ContactCreatePayload,
  ContactDuplicateCandidate,
  ContactImportBatch,
  ContactImportResult,
  ContactImportRow,
  ContactListParams,
  ContactListResult,
  ContactMutationResult,
  ContactMarkContactedResult,
  ContactRecord,
  ContactTimelineActivity,
  ContactUpdatePayload,
  CampaignRecord,
  CallLogRecord,
  CallCreatePayload,
  CallCommercialOutcome,
  CallSummaryRecord,
  CallUpdatePayload,
  ConnectorDataFreshness,
  ConnectorAccountChoiceRecord,
  ConnectorHealthStatus,
  ConnectorMetricRowPayload,
  ConnectorSetupPayload,
  ConnectorSetupStatus,
  ConnectorStatusRecord,
  ConnectorSyncPayload,
  ConnectorSyncStatus,
  CommandPaletteAction,
  CommandPaletteClinic,
  CommandPaletteQueryParams,
  CommandPaletteRecord,
  CommandPaletteRecordType,
  CommandPaletteResponse,
  CommandPaletteTargetType,
  ConsultSummaryRecord,
  CreateLocationPayload,
  CompetitorRecord,
  DashboardFunnelRecord,
  DashboardRecord,
  DashboardSummaryRecord,
  DepositRecordResponse,
  FormDefinitionRecord,
  FormSubmissionRecord,
  InviteTeamMembersPayload,
  Integration,
  InboxConversationRecord,
  WhatsAppAiReplyRecord,
  WhatsAppAiReplyStatus,
  WhatsAppAiSettingsRecord,
  WhatsAppConversationRecord,
  WhatsAppInboundPayload,
  WhatsAppInboundResult,
  InternalTaskApprovalStatus,
  InsightListParams,
  InsightRecord,
  InsightSeverity,
  InsightStatus,
  InternalTaskListParams,
  InternalTaskPayload,
  InternalTaskPriority,
  InternalTaskQaPayload,
  InternalTaskRecord,
  InternalTaskStatus,
  InternalTaskUpdatePayload,
  GrowthPackagePayload,
  GrowthPackageRecord,
  ProposalListParams,
  ProposalAcceptanceRecord,
  ProposalPayload,
  ProposalPublicPreviewRecord,
  ProposalRecord,
  ProposalSendPayload,
  ProposalShareRecord,
  ProposalStatusUpdatePayload,
  ProposalStatus,
  GrowthScoreSnapshotList,
  GrowthScoreSnapshotPayload,
  GrowthScoreSnapshotRecord,
  MessageTemplateRecord,
  ManualConsultRecord,
  ManualSpendRecord,
  MarketingConnectorType,
  PermissionRecord,
  PractitionerConversionRecord,
  HealthStatus,
  Location,
  PipelineDealListResult,
  PipelineDealMovePayload,
  PipelineDealPayload,
  PipelineDealRecord,
  PipelineDealStatus,
  PipelineDealUpdatePayload,
  PipelineStageKind,
  PipelineStagePayload,
  PipelineStageRecord,
  ResponseTimeMetricsRecord,
  RegisterClinicPayload,
  SecuritySettings,
  StoredAuthSession,
  StaffCallMetricRecord,
  TeamMember,
  TreatmentCategory,
  TaskRecord,
  TreatmentCatalogItem,
  TreatmentCatalogPayload,
  TreatmentPlanRecord,
  ReportRecord,
  ReportShareRecord,
  ReportWorkflowStatus,
  ReportWorkflowUpdatePayload,
  RevenueByChannelRecord,
  RevenueByTreatmentRecord,
  ReviewRecord,
  RoleRecord,
  SequenceRecord,
  SlaBreachRecord,
  SlaLeadRecord,
  SlaSummaryRecord,
  SopListParams,
  SopRecord,
  StrategyLogListParams,
  StrategyLogPayload,
  StrategyLogRecord,
  StrategyLogUpdatePayload,
  StaffResponseMetricRecord,
  OfferRecord,
  WebhookEndpoint,
  TwoFactorEnableResult,
  TwoFactorSetup,
  UpdateLocationPayload,
  UpdateClinicProfilePayload,
  UserPreferences,
} from "@/lib/api-types";

const accountApi = createAccountApi({
  apiRequest,
  saveAuthSession,
  toStoredSession,
});

export const api = {
  ...accountApi,
  ...createAutomationsApi(apiRequest),
  ...createClinicSetupApi(apiRequest),
  ...createCommandPaletteApi(apiRequest),
  ...createCatalogApi(apiRequest),
  ...createComplianceApi(apiRequest),
  ...createDeveloperSettingsApi(apiRequest),
  ...createOperationsApi(apiRequest),
  ...createPackagesApi(apiRequest),
  ...createProposalsApi(apiRequest),
  ...createLocationsIntegrationsApi(apiRequest),
  ...createFormsApi(apiRequest),
  ...createGrowthScoresApi(apiRequest),
  ...createSequencesApi(apiRequest),
  ...createSopsApi(apiRequest),
};

configureApiAuthRefresh(async () => {
  const session = await refreshStoredAuthSession(api.auth.refresh);
  return session?.token ?? null;
});
